---
title: "MATH319 -- Assignment 3"
author: "Pierre Visconti"
date: "January, 2024"
output:
  pdf_document:
    number_section: no
  html_document:
    df_print: paged
course: MATH319
---

Part (a): Creating functions
```{r}
# rosenbrock function
rosenbrock <- function(x1, x2) {
  out <- (x2-x1^2)^2 + (1-x1)^2
  return(out)
}

# compute the gradient
grad <- function(x1, x2) {
  c(-4*x1*(x2-x1^2)-2*(1-x1), 2*(x2-x1^2))
}

# compute the hess
hess <- function(x1, x2) {
  matrix(c(-4*x2+12*x1^2+2, -4*x1, -4*x1, 2), 2, 2) 
}
```

Part (b): Contour plot
```{r}
# make a contour plot
x1 <- seq(-5,5, length.out=100)
x2 <- x1
z <- outer(x1, x2,FUN=rosenbrock)
plot_contour <- contour(x1, x2, z, nlevels=50, main="Contour Plot of Rosenbrock Function")

# plot optimal solution
points(1,1, col="green", pch=16)

# plot initial point x0
x0 = c(1.2, 1.2)
points(x0[1], x0[2], col="blue", pch=16)

# compute and plot steepest descent for x0
grad_x0 <- grad(x0[1], x0[2])
arrows(x0[1], x0[2], -grad_x0[1], -grad_x0[2])
```

Part (c): Computing Hessian, eigenvalues, and Newton direction 
```{r}
# compute hessian at x0
hess_x0 = hess(x0[1], x0[2])
hess_x0

# compute eigenvalues for hessian at x0
eigen(hess_x0)

# make a contour plot
x1 <- seq(-5,5, length.out=100)
x2 <- x1
z <- outer(x1, x2,FUN=rosenbrock)
plot_contour <- contour(x1, x2, z, nlevels=50, main="Contour Plot of Rosenbrock Function")

# plot optimal solution
points(1,1, col="green", pch=16)

# plot initial point x0
x0 = c(1.2, 1.2)
points(x0[1], x0[2], col="blue", pch=16)

# plot steepest descent for x0
grad_x0 <- grad(x0[1], x0[2])
arrows(x0[1], x0[2], -grad_x0[1], -grad_x0[2])

# compute Newton direction for x0 and plot it
newt_x0 = -solve(hess_x0) %*% grad_x0
arrows(x0[1], x0[2], newt_x0[1], newt_x0[2])
 
```

Note that the hessian at x0 is PD therefore it is convex and has a global minimizer p_k. Therefore Newton direction is well defined and the descent direction is given by p_k= -(hess)^(-1) * grad.   

Part (d): Full algorithm implementation
```{r}
count <- 0
c1 <- 0.4
ak <- 0.8
norm_grad <- norm(c(grad_x0[1],grad_x0[2]), type="2")
pk <- -grad(x0[1], x0[2])
xk <- c(1.2, 1.2)

while(count < 500 && norm_grad < 0.000001) {
  x_ap = xk + ak*pk
  f.x_ap = rosenbrock(x_ap[1], x_ap[2])
  f.x = rosenbrock(xk[1], xk[2])
  grad.x_cap = c1*ak*t(grad(xk[1], xk[2]))*pk 
  while (f.x_ap > f.x + grad.x_cap) {
    
  }
  count = count + 1
}
```

